#!/usr/bin/env php
<?php declare(strict_types=1);

require './vendor/autoload.php';

$app = Automation\Framework\Application::instance();

$app->run();

$sleep_for = (int) config('DAEMON_SLEEP_FOR') ?? 1200;

while (true) {
    dump('Foo');

    sleep($sleep_for);
}
