#!/usr/bin/env php
<?php declare(strict_types=1, ticks=1);

require __DIR__.'/vendor/autoload.php';

use Automation\Framework\Application;
use Automation\Framework\Facades\{Slack, Console};
use Automation\Framework\Interfaces\JobInterface;
use GuzzleHttp\Exception\ConnectException;

Application::instance()->run();

app()->instantiateJobs();
app('slack')->channel('debug');

$jobs = app()->getInstancesOf(JobInterface::class);

try {
    dump(sprintf('Automation daemon has started at %s!', date('H:i')));

    while (true) {
        foreach ($jobs as $job) {
            $name = (new ReflectionObject($job))->getShortName();

            dump(sprintf('Executing "%s" job...', $name));
            
            try {
                $result = app($job);
            } catch (Throwable) {
                dump(sprintf('Failed to execute "%s" job!', $name));

                continue;
            }

            dump(sprintf('Executed "%s" job successfully!', $name));
        }

        sleep((int) app('sleep_for'));
    }
} catch (Throwable $e) {
    if ($e instanceof ConnectException) {
        Console::signal(SIGTERM);
    }

    dump(sprintf('Automation dameon got an exception at %s!', date('H:i')));

    throw $e;
}